Conditional Instructions Extension
Purdue-SoCET/RISCVBusiness pull request #37
Opened 2024-07-01 22:20 UTC by AkshathRaghav

### [[DRAFT PR]]

This PR implements the [Zicond](https://github.com/riscvarchive/riscv-zicond/blob/main/zicondops.adoc#instruction-sequences) extension (RV32ZC). 

The "Conditional" operations extension ... support conditional arithmetic and conditional-select/move operations .. philosophy.
The instructions follow the format for R-type instructions with 3 operands ... Using these instructions, branchless sequences can be implemented (typically in two-instruction sequences) without the need for instruction fusion .... provisions.

The following instructions comprise the Zicond extension:
* czero.eqz rd, rs1, rs2
* czero.nez rd, rs1, rs2

2024-07-31 21:35 UTC, devins2518 requested changes
Nice work, it's almost there. I think the makefile changes should either be removed or moved to a separate PR since they don't really belong in this one. Most of the requested changes are to just clean this up before it's merged. However, the `compare.S` test is currently failing for me, so it needs to be fixed before we can merge.

2024-07-31 21:35 UTC, devins2518 commented on Makefile
> +
This all should also probably be moved to a different PR

2024-07-31 21:35 UTC, devins2518 commented on run_tests_verilator.sh
> +done
Not sure what this adds over `run_tests_verilator.py`. Should probably delete

2024-07-31 21:35 UTC, devins2518 commented on source_code/rv32zc/rv32zc_decode.sv
> +    input [31:0] insn,
nit: add explicit logic type

2024-07-31 21:35 UTC, devins2518 commented on source_code/rv32zc/rv32zc_handler.sv
> +        y = rd_temp;
You can just assign to `y` instead of introducing the `rd_temp` variable

2024-07-31 21:35 UTC, devins2518 commented on source_code/rv32zc/rv32zc_handler.sv
> +                end
small nit: you can replace this with `y = b ? 0 : a;`

2024-07-31 21:35 UTC, devins2518 commented on source_code/rv32zc/rv32zc_handler.sv
> +                end
small nit: you can replace this with `y = b ? a : 0;`

2024-07-31 21:35 UTC, devins2518 commented on verification/self-tests/RV32I/add.S
> +RVTEST_DATA_END
revert this change

2024-07-31 21:35 UTC, devins2518 commented on verification/self-tests/RV32ZC/compare.S
> +RVTEST_RV64U
should be `RVTEST_RV32U`

2024-07-31 21:35 UTC, devins2518 commented on verification/self-tests/RV32ZC/compare.S
> +# add.S
Change name

2024-07-31 21:35 UTC, devins2518 commented on verification/self-tests/RV32ZC/compare.S
This test case is failing for me

2024-08-02 20:08 UTC, devins2518 commented on verification/self-tests/RV32ZC/compare.S
I'd rather you fix the test case rather than delete it. Or at least provide an explanation why it's not a good test case.

2024-08-02 20:11 UTC, devins2518 commented
Sorry, the multicore PR was merged which causes some conflicts with this branch. Could you rebase when you have the time

2024-08-02 20:15 UTC, AkshathRaghav commented on verification/self-tests/RV32ZC/compare.S
My bad! I thought you only wanted the stuff on the docs. I'll fix it.

2024-12-02 06:00 UTC, AkshathRaghav commented
Hey Devin! I did the rebasing. I apologize for the delay in getting this done -- I had overlooked this during the socet account re-organization during the start of sem.

2024-12-03 01:26 UTC, devins2518 approved these changes
LGTM

2024-12-03 01:26 UTC, merged