Compressed
Purdue-SoCET/RISCVBusiness pull request #6
Opened 2021-03-09 21:25 UTC by jingyin77

2021-03-09 21:52 UTC, cole-nelson requested changes
Looks good, just need a couple small changes, mostly for formatting.

2021-03-09 21:52 UTC, cole-nelson commented on rv32c.yml
> +# ISA Configurations
Remove this file please -- but update sparce.yml and example.yml to contain the new "rv32c_enabled" option. Set it to "disabled" by default.

2021-03-09 21:52 UTC, cole-nelson commented on source_code/rv32c/fetch_buffer.sv
> +        next_imem_pc = fb_if.imem_pc;
Indentation (throughout file).

2021-03-09 21:52 UTC, cole-nelson commented on source_code/rv32c/rv32c_wrapper.sv
> +module rv32c_wrapper(
We should be passing the "RESET_PC" parameter from the pipeline through to here -- we don't want to change it in more than one place.

2021-03-09 21:52 UTC, cole-nelson commented on source_code/pipelines/tspp/tspp.sv
> +  rv32c_if rv32cif
Does this need to be here in the ports? I think we could move this instantiation down to within the module.

2021-03-09 21:52 UTC, cole-nelson commented on source_code/pipelines/pipeline_wrapper.sv
> +  rv32c_if rv32cif
Does this interface need to be here in the ports? I think we could move this instantiation down to within the module.

2021-03-09 22:58 UTC, XinlueLiu commented
I think all tests got passed overall the project looks good to me. Nice Job Jing:-)

2021-03-15 22:54 UTC, cole-nelson approved these changes

2021-03-15 23:06 UTC, XinlueLiu approved these changes

2021-03-15 23:19 UTC, cchiminski approved these changes

2021-03-15 23:24 UTC, merged